Repository RolnickLab/antenna, pull requests merged in 2025-01, with the labels that each got.

#670 Fix update password form
  ui/src/components/header/user-info-dialog/user-info-form/user-info-form.module.scss
  ui/src/components/header/user-info-dialog/user-info-form/user-info-form.tsx
  ui/src/components/header/user-info-dialog/user-info-form/user-password-field.tsx
  ui/src/utils/language.ts
Labels: bug, frontend

#669 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/new-issue.md
Labels: documentation

#688 Fix background tasks from disappearing
  .envs/.local/.django
  config/settings/base.py
  requirements/base.txt
Labels: bug, backend, infrastructure
